### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jricc** [NTU-ALComLab/SliQSim#7]
Hello,
When I want to build the binary file SliQSim, I have this error:
src/main.cpp:1:10: fatal error: boost/program_options.hpp: No files or folders of this type
    1 | #include <boost/program_options.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:12 : all] Erreur 1
Could you help me?

**Comment by tfchen01** [comment]
It looks like your computer needs Boost installed. 
You could try installing Boost using a command like `sudo apt-get install libboost-all-dev`.
